### ISSUE TITLE
There is a way to extract one time a zip? because when he try to extract  a second time at second launch i have errors

### ISSUE THREAD

**Issue by quentin452** [TerraFirmaCraft-The-Final-Frontier/FileDirector#16]
```
{
	"url":
	[
		{
			"url": "https://github.com/quentin452/Biggess-Pack-Cat-Edition-Configs/releases/download/V0.90.9test3/configV0.90.9.zip",
			"folder": "config",
			"installationPolicy":
			{
				"extract": true
			}
		}
	]
}
```
[fml-client-latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/files/13659048/fml-client-latest.log)

**Comment by Lylythii** [comment]
Might be an odd method, but you could try deleting or disabling the config file that downloads & extracts the zip file, after it gets extracted. Which will result in it only being extracted once.
- [More info on modifying files here](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/wiki/Config-Type:-Modify-(since-1.8.0))

**Comment by quentin452** [comment]
yes its odd but i could try :D

**Comment by quentin452** [comment]
its seem thats not possible to use delete of disable with installationPolicy that cause errors

**Comment by quentin452** [comment]
Fixed by adding a modpackversion Property
